# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pythonstudy\pyqt5\src\AbsoluteLayout\AbsoluteLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AbsolutelayoutDemo(object):
    def setupUi(self, AbsolutelayoutDemo):
        AbsolutelayoutDemo.setObjectName("AbsolutelayoutDemo")
        AbsolutelayoutDemo.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AbsolutelayoutDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 2)
        self.doubleSpinBox_returns_min = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_returns_min.setObjectName("doubleSpinBox_returns_min")
        self.gridLayout.addWidget(self.doubleSpinBox_returns_min, 1, 0, 1, 2)
        self.doubleSpinBox_returns_max = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_returns_max.setObjectName("doubleSpinBox_returns_max")
        self.gridLayout.addWidget(self.doubleSpinBox_returns_max, 1, 2, 1, 1)
        self.doubleSpinBox_maxdrawdown_min = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_maxdrawdown_min.setObjectName("doubleSpinBox_maxdrawdown_min")
        self.gridLayout.addWidget(self.doubleSpinBox_maxdrawdown_min, 2, 0, 1, 2)
        self.doubleSpinBox_maxdrawdown_max = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_maxdrawdown_max.setObjectName("doubleSpinBox_maxdrawdown_max")
        self.gridLayout.addWidget(self.doubleSpinBox_maxdrawdown_max, 2, 2, 1, 1)
        self.doubleSpinBox_sharp_min = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sharp_min.setObjectName("doubleSpinBox_sharp_min")
        self.gridLayout.addWidget(self.doubleSpinBox_sharp_min, 3, 0, 1, 1)
        self.doubleSpinBox_sharp_max = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_sharp_max.setObjectName("doubleSpinBox_sharp_max")
        self.gridLayout.addWidget(self.doubleSpinBox_sharp_max, 3, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton1.setMaximumSize(QtCore.QSize(300, 300))
        self.pushButton1.setObjectName("pushButton1")
        self.horizontalLayout.addWidget(self.pushButton1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        AbsolutelayoutDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AbsolutelayoutDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        AbsolutelayoutDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AbsolutelayoutDemo)
        self.statusbar.setObjectName("statusbar")
        AbsolutelayoutDemo.setStatusBar(self.statusbar)
        self.label_5.setBuddy(self.doubleSpinBox_sharp_min)

        self.retranslateUi(AbsolutelayoutDemo)
        QtCore.QMetaObject.connectSlotsByName(AbsolutelayoutDemo)
        AbsolutelayoutDemo.setTabOrder(self.doubleSpinBox_returns_min, self.doubleSpinBox_returns_max)
        AbsolutelayoutDemo.setTabOrder(self.doubleSpinBox_returns_max, self.doubleSpinBox_maxdrawdown_min)
        AbsolutelayoutDemo.setTabOrder(self.doubleSpinBox_maxdrawdown_min, self.doubleSpinBox_maxdrawdown_max)
        AbsolutelayoutDemo.setTabOrder(self.doubleSpinBox_maxdrawdown_max, self.doubleSpinBox_sharp_min)
        AbsolutelayoutDemo.setTabOrder(self.doubleSpinBox_sharp_min, self.doubleSpinBox_sharp_max)
        AbsolutelayoutDemo.setTabOrder(self.doubleSpinBox_sharp_max, self.pushButton1)

    def retranslateUi(self, AbsolutelayoutDemo):
        _translate = QtCore.QCoreApplication.translate
        AbsolutelayoutDemo.setWindowTitle(_translate("AbsolutelayoutDemo", "MainWindow"))
        self.label_3.setText(_translate("AbsolutelayoutDemo", "收益"))
        self.label_4.setText(_translate("AbsolutelayoutDemo", "最大回撤"))
        self.label_5.setText(_translate("AbsolutelayoutDemo", "&sharp比"))
        self.label.setText(_translate("AbsolutelayoutDemo", "最小值"))
        self.label_2.setText(_translate("AbsolutelayoutDemo", "最大值"))
        self.pushButton1.setText(_translate("AbsolutelayoutDemo", "开始"))

